# Generated by Django 5.0.1 on 2024-01-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=50)),
                ('dst', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('capacity', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', related_query_name='bus', to='booking.route')),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('booked', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', related_query_name='seat', to='booking.bus')),
            ],
            options={
                'verbose_name_plural': 'Seats',
            },
        ),
    ]
