# Generated by Django 5.0.1 on 2024-01-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AlterField(
            model_name='route',
            name='dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_with_dst', related_query_name='route_with_dst', to='booking.city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_with_src', related_query_name='route_with_src', to='booking.city'),
        ),
    ]
